# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"\xeb\x01\n\x05\x45vent\x12\x15\n\rconnection_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12$\n\x07payload\x18\x03 \x03(\x0b\x32\x13.Event.PayloadEntry\x12\"\n\x06header\x18\x04 \x03(\x0b\x32\x12.Event.HeaderEntry\x1a\x36\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value:\x02\x38\x01\x1a\x35\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value:\x02\x38\x01\"v\n\x05Value\x12\x13\n\tstr_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x14\n\nbool_value\x18\x03 \x01(\x08H\x00\x12$\n\x0cnested_value\x18\x04 \x01(\x0b\x32\x0c.NestedValueH\x00\x42\x07\n\x05value\"n\n\x0bNestedValue\x12(\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x18.NestedValue.FieldsEntry\x1a\x35\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Value:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT_PAYLOADENTRY']._loaded_options = None
  _globals['_EVENT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_EVENT_HEADERENTRY']._loaded_options = None
  _globals['_EVENT_HEADERENTRY']._serialized_options = b'8\001'
  _globals['_NESTEDVALUE_FIELDSENTRY']._loaded_options = None
  _globals['_NESTEDVALUE_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_EVENT']._serialized_start=16
  _globals['_EVENT']._serialized_end=251
  _globals['_EVENT_PAYLOADENTRY']._serialized_start=142
  _globals['_EVENT_PAYLOADENTRY']._serialized_end=196
  _globals['_EVENT_HEADERENTRY']._serialized_start=198
  _globals['_EVENT_HEADERENTRY']._serialized_end=251
  _globals['_VALUE']._serialized_start=253
  _globals['_VALUE']._serialized_end=371
  _globals['_NESTEDVALUE']._serialized_start=373
  _globals['_NESTEDVALUE']._serialized_end=483
  _globals['_NESTEDVALUE_FIELDSENTRY']._serialized_start=430
  _globals['_NESTEDVALUE_FIELDSENTRY']._serialized_end=483
# @@protoc_insertion_point(module_scope)
